# ~~~~~~~~ --order of sourcing-- ~~~~~~~~ #
# (ignoring /etc/* files)
# $ZDOTDIR/.zshenv
# $ZDOTDIR/.zprofile <-- XOR .zlogin  (by intention, but not enforced)
# $ZDOTDIR/.zshrc
# $ZDOTDIR/.zlogin  <-- XOR .zprofile  (by intention, but not enforced)
# $ZDOTDIR/.zlogout
#
# NOTES: env: sourced each shell
#        rc: sourced each *interactive* shell
#        profile|x|login : sourced each *login* shell 
#                           login-shells often not opened in linux, but
#                           opened with each new window or tab in macOS
#


# ########################## --Path Exports-- ###################### #
# ----------- ZSH ----------- 
export ZDOTDIR=$HOME/.config/zsh
export HISTFILE=$HOME/.zsh_history  # default
export SHELL_SESSIONS_DISABLE=1
# sets the xsh_history file in its typical location, preventing it from
# being placed in our git versioned  ZSH/ directory (due to $ZDOTDIR setting in .zshenv)
# prevent a `zsh_sessions` file from being generated by the default macOS terminal app

# ----------- starship (terminal prompt) ----------- 
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml

# ----------- git ----------- 
# This is code is provided commented out for easy integration if desired.
# It will tell git to look for its config files in a folder labeled "git_global"
# inside the ".config" folder in your home directory.
# It's quite nice if you version control your configuration files, allowing you to
# include global git and global .gitignore settings.
#
# export GIT_CONFIG_GLOBAL=$HOME/.config/git_global/.gitconfig
# "git_config_(global/system)": 
#       "..._global"" is for user (usually in "$HOME/...")
#       "..._system" is for system/computer (usually in "/etc/...")

# ----------- Go ----------- 
# note: these came up when trying to make the PagerDuty-Terraform Provider
export GOPATH=$HOME/go  #default
export PATH=$PATH:$GOPATH

# ----------- Python -----------
# Poetry is being used for virtual-env and dependency managment
# I am moving its config files to coreside with other core "dot"files
export POETRY_CONFIG_DIR=$HOME/.config/pypoetry
export POETRY_CACHE_DIR=$HOME/Library/Caches/pypoetry  # default
export POETRY_DATA_DIR=$HOME/Library/Application\ Support/pypoetry  # default

# ----------- Rust ----------- 
export PATH=$PATH:$HOME/.cargo/bin  # default


# ########################## --Environment Sourcing-- ###################### #
# NOTE: "." is posix ~= of "source"
#   in zsh: 
#       "." looks in $PATH first and closes shell if it fails to find target
#       "source" looks in current directory first and only closes shell 
#           if run in posix mode

# ----------- Sourcing Rust-relevant environment variables ----------- 
# . "$HOME/.cargo/env"
# ^ this is just a PATH check and export if not found (made to be easily overidden)
# unecessary, as we are directly exporting the PATH above, but kept for reference
